from abc import ABC, abstractmethod
from typing import BinaryIO


class ResumeStorageError(Exception):
    """Base class for resume storage failures."""


class EmptyResumeError(ResumeStorageError):
    pass


class ResumeTooLargeError(ResumeStorageError):
    def __init__(self, max_bytes: int) -> None:
        super().__init__(f"Resume exceeds the maximum size of {max_bytes} bytes")
        self.max_bytes = max_bytes


class UnsupportedResumeTypeError(ResumeStorageError):
    def __init__(self) -> None:
        super().__init__("Resume must be a PDF, DOC or DOCX file")


class ResumeNotFoundError(ResumeStorageError):
    pass


class ResumeStorage(ABC):
    @abstractmethod
    def save(self, stream: BinaryIO) -> str:
        """Validate and store the content, returning an opaque storage key.

        The client's filename is deliberately not a parameter: the key is
        generated by the server.
        """

    @abstractmethod
    def open(self, key: str) -> BinaryIO:
        """Open a stored resume for reading; raises ResumeNotFoundError."""

    @abstractmethod
    def delete(self, key: str) -> None:
        """Remove a stored resume; a missing resume is not an error."""
