import io
import logging
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import PurePath
from typing import BinaryIO

from app.data_acceses.email_event_data_access import EmailEventDataAccess
from app.data_acceses.lead_data_access import LeadDataAccess
from app.models import EmailEvent, EmailKind, Lead, LeadState
from app.schemas.lead import LeadCreate
from app.services.lead_exceptions import (
    InvalidStateTransitionError,
    LeadNotFoundError,
)
from app.storage.resume_storage import ResumeStorage
from app.storage.resume_validation import content_type_for_extension

logger = logging.getLogger(__name__)


@dataclass
class ResumeDownload:
    stream: BinaryIO
    content_type: str
    extension: str
    original_filename: str | None

_ALLOWED_TRANSITIONS: dict[LeadState, set[LeadState]] = {
    LeadState.PENDING: {LeadState.REACHED_OUT},
    LeadState.REACHED_OUT: set(),
}


class LeadService:
    def __init__(
        self,
        data_access: LeadDataAccess,
        resume_storage: ResumeStorage,
        email_event_data_access: EmailEventDataAccess,
        attorney_emails: list[str],
        max_confirmations_per_address_per_day: int = 3,
    ) -> None:
        self._data_access = data_access
        self._resume_storage = resume_storage
        self._email_events = email_event_data_access
        self._attorney_emails = attorney_emails
        self._max_confirmations = max_confirmations_per_address_per_day

    def create_lead(
        self,
        data: LeadCreate,
        resume_bytes: bytes,
        resume_filename: str,
        honeypot: str = "",
    ) -> Lead | None:
        """Create a lead, or return None if the honeypot field was filled.

        Real prospects never see the honeypot field, so a filled one means a
        bot: the submission is silently discarded and nothing is stored or sent.
        """
        if honeypot.strip():
            logger.info("Honeypot triggered; submission discarded")
            return None
        # The stored name is generated by ResumeStorage. The client's filename
        # is kept only as text, to name the download later.
        resume_key = self._resume_storage.save(io.BytesIO(resume_bytes))
        try:
            lead = self._data_access.add(
                Lead(
                    first_name=data.first_name,
                    last_name=data.last_name,
                    email=data.email,
                    resume_path=resume_key,
                    resume_filename=resume_filename.strip()[:255] or None,
                )
            )
            # PENDING email rows join the lead's transaction, so a saved lead
            # always has a record of the emails owed for it.
            recipients = []
            if self._may_send_confirmation(data.email):
                recipients.append((EmailKind.PROSPECT_CONFIRMATION, data.email))
            else:
                # The address is typed by an anonymous visitor, so without a cap
                # the form could be used to flood someone else's inbox.
                logger.info("Confirmation email skipped: daily limit for an address")
            recipients += [
                (EmailKind.ATTORNEY_NOTIFICATION, attorney)
                for attorney in self._attorney_emails
            ]
            for kind, recipient in recipients:
                self._email_events.add(
                    EmailEvent(lead_id=lead.id, kind=kind, recipient=recipient)
                )
            self._data_access.commit()
        except Exception:
            self._resume_storage.delete(resume_key)
            raise
        return lead

    def _may_send_confirmation(self, address: str) -> bool:
        since = datetime.now(timezone.utc) - timedelta(days=1)
        sent = self._email_events.count_since(
            address, EmailKind.PROSPECT_CONFIRMATION, since
        )
        return sent < self._max_confirmations

    def get_lead(self, lead_id: str) -> Lead:
        lead = self._data_access.get_by_id(lead_id)
        if lead is None:
            raise LeadNotFoundError(lead_id)
        return lead

    def open_resume(self, lead_id: str) -> ResumeDownload:
        """Open a lead's resume; raises LeadNotFoundError or ResumeNotFoundError."""
        lead = self.get_lead(lead_id)
        stream = self._resume_storage.open(lead.resume_path)
        extension = PurePath(lead.resume_path).suffix
        return ResumeDownload(
            stream=stream,
            content_type=content_type_for_extension(extension),
            extension=extension,
            original_filename=lead.resume_filename,
        )

    def list_leads(
        self, state: LeadState | None = None, limit: int = 20, offset: int = 0
    ) -> tuple[list[Lead], int]:
        leads = self._data_access.list(state=state, limit=limit, offset=offset)
        return leads, self._data_access.count(state=state)

    def mark_reached_out(self, lead_id: str, attorney_email: str) -> Lead:
        lead = self.get_lead(lead_id)
        target = LeadState.REACHED_OUT
        if target not in _ALLOWED_TRANSITIONS[lead.state]:
            raise InvalidStateTransitionError(lead.state, target)

        # The state check above can be stale by the time we write, so the write
        # itself is conditional: only the caller who finds the lead still in its
        # current state wins, and the other gets the same error as a repeat.
        won = self._data_access.update_if_state(
            lead_id,
            lead.state,
            state=target,
            reached_out_at=datetime.now(timezone.utc),
            reached_out_by=attorney_email,
        )
        if not won:
            self._data_access.refresh(lead)
            raise InvalidStateTransitionError(lead.state, target)
        self._data_access.commit()
        return lead
