import io
from datetime import datetime, timezone

from app.data_acceses.lead_data_access import LeadDataAccess
from app.models import Lead, LeadState
from app.schemas.lead import LeadCreate
from app.services.lead_exceptions import (
    InvalidStateTransitionError,
    LeadNotFoundError,
)
from app.storage.resume_storage import ResumeStorage

_ALLOWED_TRANSITIONS: dict[LeadState, set[LeadState]] = {
    LeadState.PENDING: {LeadState.REACHED_OUT},
    LeadState.REACHED_OUT: set(),
}


class LeadService:
    def __init__(
        self, data_access: LeadDataAccess, resume_storage: ResumeStorage
    ) -> None:
        self._data_access = data_access
        self._resume_storage = resume_storage

    def create_lead(
        self, data: LeadCreate, resume_bytes: bytes, resume_filename: str
    ) -> Lead:
        # resume_filename is accepted so callers pass what the client sent, but
        # it is never used: the stored name is generated by ResumeStorage.
        resume_key = self._resume_storage.save(io.BytesIO(resume_bytes))
        try:
            lead = self._data_access.add(
                Lead(
                    first_name=data.first_name,
                    last_name=data.last_name,
                    email=data.email,
                    resume_path=resume_key,
                )
            )
            self._data_access.commit()
        except Exception:
            self._resume_storage.delete(resume_key)
            raise
        return lead

    def get_lead(self, lead_id: str) -> Lead:
        lead = self._data_access.get_by_id(lead_id)
        if lead is None:
            raise LeadNotFoundError(lead_id)
        return lead

    def list_leads(
        self, state: LeadState | None = None, limit: int = 20, offset: int = 0
    ) -> tuple[list[Lead], int]:
        leads = self._data_access.list(state=state, limit=limit, offset=offset)
        return leads, self._data_access.count(state=state)

    def mark_reached_out(self, lead_id: str, attorney_email: str) -> Lead:
        lead = self.get_lead(lead_id)
        target = LeadState.REACHED_OUT
        if target not in _ALLOWED_TRANSITIONS[lead.state]:
            raise InvalidStateTransitionError(lead.state, target)

        lead.state = target
        lead.reached_out_at = datetime.now(timezone.utc)
        lead.reached_out_by = attorney_email
        self._data_access.commit()
        return lead
